### ISSUE TITLE
Tests!!!

### ISSUE THREAD

**Issue by eriq-augustine** [linqs/pacman#1]
The base code came with no tests.
Of course unit tests are difficult to write after everything has been implemented, but some base functionality tests (just doing full runs) would be a good start.

**Comment by eriq-augustine** [comment]
This includes setting up Travis CI (which is pretty easy).

**Comment by eriq-augustine** [comment]
What about a test that just imports all the files?
Wouldn't the linter already do that?

**Comment by tsalh** [comment]
I'm working on testing

**Comment by eriq-augustine** [comment]
The testing infrastructure is complete in c535b52be5e982a84bed3913a3201a323100bc41.
