### ISSUE TITLE
FrameTime flag synchronization

### ISSUE THREAD

**Issue by boomitsnoom** [linqs/pacman#14]
The pacman.py code currently enables a frameTime flag as a command line argument. I was wondering if the same could be applied to capture.py?
The frameTime in capture.py is currently hardcoded to 0 and would be great if it could be tunable as a command line argument, similar to pacman.py.

**Comment by eriq-augustine** [comment]
We can generalize this to aligning all the options (and code) in pacman and capture.

**Comment by eriq-augustine** [comment]
Obviated by #4 .
Instead, we now have the `--fps` option.
