### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by eriq-augustine** [linqs/pacman#15]
Our code needs some style.

We will need to pick both a style and linter.
For the style, PEP 8 is a given, but do we want any variants/relaxations on it.
There are several good options for linters.
I am more inclined to `pylint`, but can be sold on others.

Finally, we will need the linter hooked into our testing/CI.
This is important, because we will want to later run a style check as part of the autograder.

Note that the main assignee of this issue is not responsible for updating all files.
Once the style is decided upon, then all touched files will need to be brought up to standard before PRs are accepted on them.
(This will require two PRs: one just for the style, then one for the actual issue.)

**Comment by eriq-augustine** [comment]
They style tsar (resolver of this issue) should also weigh in on `import x` vs `from x import y`.
I am typically a fan of the former (so that uses are more explicit), but because of some longer namespaces, we may want to stray towards the later.

Or, we can maybe have a compromise were we will can use `from x import y` only where y is a module (file).

**Comment by kcarella** [comment]
Hey @eriq-augustine , this is the comment you requested.

**Comment by eriq-augustine** [comment]
In the future, try to post more complete comments.
Remember, not everyone has the context of our conversation, and this conversation stays around for anyone to look through.

**Comment by eriq-augustine** [comment]
Style guide is up here: https://github.com/linqs/pacman/wiki/Style-Guide
CI was complete here: a9bc69d3d4f18da3449534e0a60ad82b1a00c016
