### ISSUE TITLE
pacai.util.util Needs to be Broken Up

### ISSUE THREAD

**Issue by eriq-augustine** [linqs/pacman#20]
`pacai.util.util` (besides being a bad name) contains too many unrelated things.
It should be broken up into more topical files (with better names).

**Comment by tsalh** [comment]
Addressing this issue will also involve fixing the util test, so maybe I should address this issue?

**Comment by eriq-augustine** [comment]
I wouldn't really say it would be "fixing" the util test, it is more just changing the util test.
Regardless, this would be a good one to take.

**Comment by tsalh** [comment]
close this issue?
