### ISSUE TITLE
Consistent Bin Interface

### ISSUE THREAD

**Issue by eriq-augustine** [linqs/pacman#25]
Make a consistent interface/main for all `pacai.bin` classes.
Some of the binary don't even have a `main()`, they just use a main guard.
This means we can't invoke the main functionality directly from other Python code.

**Comment by eriq-augustine** [comment]
When this is implemented, add in bin tests for the fixed files.

**Comment by tsalh** [comment]
My next issue

**Comment by eriq-augustine** [comment]
This has been fixed here and there in several commits.
