### ISSUE TITLE
raiseNotDefined() Should Throw, Not Exit

### ISSUE THREAD

**Issue by eriq-augustine** [linqs/pacman#27]
`raiseNotDefined()` should throw an exception, not just exit (like a jerk).
Also, we want to limit the use of this as much as we can.
Maybe we can just throw on the spot instead.

**Comment by tsalh** [comment]
If I'm not mistaken, does this just involve changing the function's code to simply:
raise Exception("Method not implemented: %s" % inspect.stack()[1][3])?

**Comment by eriq-augustine** [comment]
Close, I don't want to inspect the stack.
We can just throw a `NotImplementedError` directly.

To limit the use, we change the student code.
Do we need it in all places?
If it is just a few places, can we just throw in those places instead of calling another method?
Should we just return a default value instead?

**Comment by tsalh** [comment]
I think for some functions it's necessary such as the DFS, BFS, UCS, and A*. But there are a few functions such as a game state evaluation function or heuristic methods should just return default values.

**Comment by eriq-augustine** [comment]
Complete in e9da7356d64eb7adba08967284b7e49a6873cfdf.
