### ISSUE TITLE
Review Counter Usage

### ISSUE THREAD

**Issue by eriq-augustine** [linqs/pacman#29]
Review the usage of Counter and see if it is actually needed, or if we can just trash it.
I would prefer if we used just raw dictionaries.

**Comment by tsalh** [comment]
Reviewing my code during the Spring iteration for the usage of the counter object, I didn't utilize any of the methods associated with the counter object. Such as the methods in probability.py for a Counter object. So I don't see a purpose for the data structure.

**Comment by eriq-augustine** [comment]
Counter was removed and replaced with standard dicts.
#49 d49441ea5ed9a114a65f2037298c7cd98b8b7cc2
