### ISSUE TITLE
Scared Ghost Crash

### ISSUE THREAD

**Issue by eriq-augustine** [linqs/pacman#35]
When running a the new replay unit tests, I got a random crash from pacman.
For some reason, a scared ghost (the blue one in this run) tried to go into a wall.
This does not happen all the time.

Attached are the replay and output from this run.
[ghost_crash.tar.gz](https://github.com/linqs/pacman/files/3618720/ghost_crash.tar.gz)

**Comment by tsalh** [comment]
The same crash has occurred when I was running the replay unit test on capture, as you've previously said it does not happen all the time.
