### ISSUE TITLE
Seeds in Pacman and Capture

### ISSUE THREAD

**Issue by eriq-augustine** [linqs/pacman#38]
We should be able to pass a seed to both of these via the command line.
There should be no option to pass a constant seed (the `--fixRandomSeed` options),
instead we should specify a seed like:
```
--seed 123
```

**Comment by tsalh** [comment]
I'll work on this.

**Comment by eriq-augustine** [comment]
Sure.
There is a dependency on #7 , but Connor is finishing that up soon.

**Comment by tsalh** [comment]
I was thinking abt that, I'll wait for Connor to finish up his issue, I will work on this issue afterwards. For the time being I'll work on another issue.

**Comment by eriq-augustine** [comment]
I don't want you having two issues so close to our freeze date (since I will just blaze through all of the unclaimed issues that we want to have in before the freeze).
Decide if you want to leave or pick up this one.

**Comment by tsalh** [comment]
I'll pick up this issue and wait for Connor.

**Comment by eriq-augustine** [comment]
Connor is done, you are good to go.

**Comment by eriq-augustine** [comment]
Complete in 22cea584f29f2a7a3d336006496eca1c18a907a0.
