### ISSUE TITLE
Misleading search agent instantiation logs

### ISSUE THREAD

**Issue by FabAlchemy** [linqs/pacman#57]
The instantiation of certain search agents (`AStarCornersAgent` for instance) [bypasses the parent constructor](https://github.com/linqs/pacman/blob/master/pacai/agents/search/corners.py). As a result, the logs are misleading, because they are printed when the parent class is instantiated with the default values.

```console
# python3 -m pacai.bin.pacman --layout mediumCorners --pacman AStarCornersAgent --null-graphics
INFO - 2022-01-15 21:56:04,233 - [SearchAgent] using problem type pacai.core.search.position.PositionSearchProblem.
INFO - 2022-01-15 21:56:04,233 - [SearchAgent] using function pacai.student.search.depthFirstSearch.
```

**Comment by eriq-augustine** [comment]
Fixed by OP in 472f70875b0c80a6e76b0d50932a8f48b1c6937e.
