### ISSUE TITLE
Use Logging

### ISSUE THREAD

**Issue by eriq-augustine** [linqs/pacman#8]
For non-UI (text UI) code, we should switch over to actually logging instead of prints.
This will make it easier to handle different verbose levels.

**Comment by eriq-augustine** [comment]
Note that this specific issue does not cover adding in all the logging.
Just setting up the infrastructure and switching existing prints to logs.

**Comment by nrharido** [comment]
Im doing logging

**Comment by eriq-augustine** [comment]
Initial infrastructure and conversion of prints complete in ccc139b7232370fb745689b0c4ad4acb11a8231c.
